export interface TeamMatchesYear {
    key:                 string;
    name:                string;
    event_code:          string;
    event_type:          number;
    district:            District;
    city:                string;
    state_prov:          string;
    country:             string;
    start_date:          string;
    end_date:            string;
    year:                number;
    short_name:          string;
    event_type_string:   string;
    week:                number;
    address:             string;
    postal_code:         string;
    gmaps_place_id:      string;
    gmaps_url:           string;
    lat:                 number;
    lng:                 number;
    location_name:       string;
    timezone:            string;
    website:             string;
    first_event_id:      string;
    first_event_code:    string;
    webcasts:            Webcast[];
    division_keys:       string[];
    parent_event_key:    string;
    playoff_type:        number;
    playoff_type_string: string;
}

export interface District {
    abbreviation: string;
    display_name: string;
    key:          string;
    year:         number;
}

export interface Webcast {
    type:    string;
    channel: string;
    file:    string;
}

export interface SimpleTeamsAtEvent {
    key:         string;
    team_number: number;
    nickname:    string;
    name:        string;
    city:        string;
    state_prov:  string;
    country:     string;
}

export interface TeamsAtEvent {
    key:               string;
    team_number:       number;
    nickname:          string;
    name:              string;
    city:              string;
    state_prov:        string;
    country:           string;
    address:           string;
    postal_code:       string;
    gmaps_place_id:    string;
    gmaps_url:         string;
    lat:               number;
    lng:               number;
    location_name:     string;
    website:           string;
    rookie_year:       number;
    motto:             string;
    home_championship: {year:string};
}

// Generated by https://quicktype.io

export interface TeamEventsYear {
    key:                 string;
    name:                string;
    event_code:          string;
    event_type:          number;
    district:            District;
    city:                string;
    state_prov:          string;
    country:             string;
    start_date:          string;
    end_date:            string;
    year:                number;
    short_name:          string;
    event_type_string:   string;
    week:                number;
    address:             string;
    postal_code:         string;
    gmaps_place_id:      string;
    gmaps_url:           string;
    lat:                 number;
    lng:                 number;
    location_name:       string;
    timezone:            string;
    website:             string;
    first_event_id:      string;
    first_event_code:    string;
    webcasts:            Webcast[];
    division_keys:       string[];
    parent_event_key:    string;
    playoff_type:        number;
    playoff_type_string: string;
}

export interface District {
    abbreviation: string;
    display_name: string;
    key:          string;
    year:         number;
}

export interface Webcast {
    type:    string;
    channel: string;
    file:    string;
}


